### ISSUE TITLE
No wechat

### ISSUE THREAD

**Issue by dsakura** [starxg/DeepL-Crack#1]
Hello! I dont have the wechat for qr code, and the telegram bot doesnt do anything, how proceed with telegram? Thanks

**Comment by starxg** [comment]
![img](https://github.com/starxg/DeepL-Crack/assets/34997494/61d59e98-a746-43f2-93ec-dd451fa40240)

**Comment by dsakura** [comment]
I told that i click on it, and open a bot on telegram that dont help. What supose to do with the bot on telegram? Thanks

**Comment by starxg** [comment]
reinstall usersceipt. new version 1.1.5
